FROM openjdk:11

COPY ./target/department-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app/

RUN sh -c 'touch department-0.0.1-SNAPSHOT.jar'
EXPOSE 9001

ENTRYPOINT ["java","-jar","department-0.0.1-SNAPSHOT.jar"]